<?php return array (
  'app_name' => 'Pan Events',
  'app_url' => 'http://localhost:8000',
  'paystack_url' => 'https://api.paystack.co/transaction',
  'callback_url' => 'url',
  'channels' => 
  array (
    0 => 'card',
    1 => 'bank',
    2 => 'ussd',
    3 => 'qr',
    4 => 'mobile_money',
    5 => 'bank_transfer',
    6 => 'eft',
  ),
  'paystack_secret_key' => 'sk_test_7004990c2d03ef36c64ebd588c953d1c2e015f73',
  'site_name' => 'PAN Events',
  'site_slogan' => 'Paediatric Association of Nigeria (PAN) | Events Portal',
  'phone_number' => '+2348033071367',
  'email' => 'info@pan-ng.org',
  'facebook' => 'https://www.facebook.com/PANigeria',
  'twitter' => 'https://twitter.com/pan_ngr',
  'instagram' => 'https://www.instagram.com/pan_ngr',
  'youtube' => 'https://www.linkedin.com/in/pan-ng-paediatric-association-of-nigeria/',
  'smtp_username' => 'notifications@events.pan-ng.org',
  'smtp_password' => '@events.pan-ng.org',
  'smtp_host' => 'pan-ng.org',
  'smtp_from_address' => 'notifications@events.pan-ng.org',
  'smtp_from_name' => 'Paediatric Association of Nigeria (PAN) | Events Portal',
  'smtp_mail_port' => '465',
  'paystack_key' => 'sk_test_7004990c2d03ef36c64ebd588c953d1c2e015f73',
  'extra_charge' => '750',
  'meta_title' => 'Paediatric Association of Nigeria (PAN) | Events Portal',
  'meta_description' => 'Paediatric Association of Nigeria (PAN) | Events Portal',
  'meta_keywords' => 'PAN, events, conference, Paediatric',
  'site_logo' => 'logo/1693803846_logo.svg',
  'sms_username' => 'speedlinkng2013',
  'sms_password' => '1234567',
  'sms_sender' => 'PAN Events',
  'bank_name' => 'First Bank of Nigeria',
  'account_name' => 'Paediatric Association of Nigeria',
  'account_number' => '2016685143',
  'payment_split_code' => 'SPL_vyTIZZIsLS',
);